FROM ${FROM_DOCKERFILE_REGISTRY}centos${FROM_DOCKERFILE_TAG}
MAINTAINER bikeemotion

RUN PKGS_TO_INSTALL="\
      cronie-1.4.11-* \
      docker-1.12.6-*" && \
    echo "Validating the existence of the following packages:" && \
    for PKG in ${PKGS_TO_INSTALL}; do \
      (echo "${PKG}" && yum info ${PKG} >> /dev/null 2>&1) || exit 1; \
    done && \
    yum install -y --setopt=tsflags=nodocs ${PKGS_TO_INSTALL} && \
    rm -fr /var/cache/yum/* && \
    yum clean all && \
    rm -rf /etc/cron.daily/* && \
    rm -rf /etc/cron.hourly/*

COPY root_fs/ /

#CMD ["infinite_loop"]
CMD ["crond","-n","-x","load"]

